import './reset.css';
import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from '@/contextAPI/provider/providers';
import Header from './components/Header';
import Footer from './components/Footer';
import UserMenu from './components/UserMenu';
import SearchBar from './components/SearchBar';
import React from 'react';
import AuthProvider from './api/auth/[...nextauth]/authProvider';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang='en'>
			<body className={`${inter.className} flex-col`}>
				<Providers>
					<SearchBar />

					<UserMenu />
					<Header />
					<AuthProvider>{children}</AuthProvider>
					<Footer />
				</Providers>
			</body>
		</html>
	);
}
