import './reset.css'
import './globals.css'
import type { Metadata } from 'next'
import Providers from '@/contextAPI/provider/providers'
import Header from './components/Header'
import Footer from './components/Footer'
import UserMenu from './components/UserMenu'
import SearchBar from './components/SearchBar'
import LoginForm from './components/LoginForm'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
     
    <body className='flex-col'>
      <Providers>
        <SearchBar />
        <LoginForm />
        <UserMenu />
        <Header />
        {children}
        <Footer />
      </Providers>
    </body>
    
    </html>
  )
}
